//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolutionDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cellphone_Battery1
    {
        public string Name { get; set; }
        public string Expr1 { get; set; }
        public string Expr3 { get; set; }
        public string Expr5 { get; set; }
        public string Expr6 { get; set; }
        public string Solution { get; set; }
    }
}
