//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolutionDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cellphone
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int SubCategory_Id { get; set; }
    
        public virtual Cellphone_Hardware Cellphone_Hardware { get; set; }
        public virtual Cellphone_Software Cellphone_Software { get; set; }
    }
}
