//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolutionDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Info
    {
        public string Name { get; set; }
        public int Number { get; set; }
        public string Mail { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public int zip { get; set; }
    }
}
